Update bookmarkthis

diff --git a/bookmarkthis b/bookmarkthis
--- a/bookmarkthis
+++ b/bookmarkthis
@@ -1,41 +1,47 @@
 #!/bin/sh
 
-# Variables
-bookmark=""
-dir="$HOME/Documents/bookmarks"
-file="$dir/bookmarks.txt"
-title=""
+# Define variables
+DIR="$HOME/Documents/bookmarks"
+FILE="$DIR/bookmarks.txt"
+TITLE=""
 
-# Defining 'bookmark' as what is selected
-# Uncomment the next one if you want what is on yout clipboard to be bookmarket. Not recommended.
-# bookmark="$(xclip -selection clipboard -o)"
-bookmark="$(xclip -o)"
-
-# Verify if 'bookmark' is empty
-if [ -z "$bookmark" ]; then
-    notify-send "Oops." "Nothing to add!"
+# Get selected text
+BOOKMARK="$(xclip -selection primary -o)"
+# Verify bookmark is not empty
+if [ -z "$BOOKMARK" ]; then
+    notify-send "Error" "No text selected"
     exit 1
 fi
 
-# Create the bookmarks directory if it doesn't already exist
-if [ ! -d "$dir" ]; then
-    mkdir -p "$dir"
+# Create bookmarks directory if it doesn't exist
+if [ ! -d "$DIR" ]; then
+    mkdir -p "$DIR"
 fi
 
-# Check if bookmark file exists
-if [ ! -f "$file" ]; then
-    touch "$file"
+# Create bookmarks file if it doesn't exist
+if [ ! -f "$FILE" ]; then
+    touch "$FILE"
 fi
 
-# Set the 'title' variable to the bookmark title chosen by the user via dmenu
-title="$(echo "" | dmenu -p "Enter title for bookmark (press ENTER to save untitled):")"
+# Check if bookmark already exists in file
+if grep -qFx "$BOOKMARK" "$FILE"; then
+    notify-send "Error" "Bookmark already exists"
+    exit 1
+fi
 
-# Add the bookmark at the end of the snippets file
-if [ -n "$title" ]; then
-    string="$bookmark #$title"
+# Prompt user for bookmark title
+TITLE=$(echo "" | dmenu -p "Enter bookmark title (or press ENTER to save without a title)")
+
+# Add bookmark to file
+if [ -n "$TITLE" ]; then
+    echo "$BOOKMARK #$TITLE" >> "$FILE"
 else
-    string="$bookmark"
+    echo "$BOOKMARK" >> "$FILE"
 fi
 
-echo "$string" >> "$file"
-notify-send "Added!" "The following bookmark has been added to the snippets file: $bookmark"
+# Display success message
+if [ $? -eq 0 ]; then
+    notify-send "Success" "Bookmark added"
+else
+    notify-send "Error" "Failed to add bookmark"
+fi
